# -*- coding: utf-8 -*-
"""youtube_spam_comment_classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hEAF6PW1I50Xn_xyxJGmiRcz9c_Ye_Jn
"""

from google.colab import drive
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

drive.mount('/content/drive', force_remount=True)
!ls '/content/drive/MyDrive/Youtube_data.csv'

data = pd.read_csv('/content/drive/MyDrive/Youtube_data.csv')
df = pd.DataFrame(data)
df.head()

df = df.drop(['Unnamed: 0', 'COMMENT_ID', 'AUTHOR', 'DATE'], axis=1)

df.head(3)

df.isnull().sum()

df['CLASS'].value_counts()

inputs = df['CONTENT']
target = df['CLASS']

x_train, x_test, y_train, y_test = train_test_split(inputs, target, test_size=0.15, random_state=365, stratify=target)

y_train.value_counts(normalize=True)

y_test.value_counts()

vectorizer = CountVectorizer()
x_train_transf = vectorizer.fit_transform(x_train)
x_test_transf = vectorizer.fit_transform(x_test)

x_test_transf.shape

x_train_transf.shape

